---
title: "Homework 6 Solutions"
author: Laura Gomez
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
library(tidyverse)
library(p8105.datasets)
library(dplyr)
require(gridExtra)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = 0.6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


# Problem 1


# Problem 2

Import and tidy the following data set:
```{r Birth_weight_df}
Birth_weight_df = read_csv("./Data/birthweight (1).csv") %>%
  mutate(babysex = as.character(babysex), babysex = case_when(babysex == 1 ~ "male", babysex == 2 ~ "female" )) %>%
  mutate(frace = as.character(frace),
    frace = case_when(
      frace == 1 ~ "White", 
      frace == 2 ~ "Black", 
      frace == 3 ~ "Asian",
      frace == 4 ~ "Puerto Rican",
      frace == 8 ~ "Other",
      frace == 9 ~ "Unknown"
      )) %>%
  mutate( malform = as.character(malform), malform = case_when(malform == 0 ~ "absent", malform == 1 ~ "present" ))  %>%
  mutate( mrace = as.character(mrace), 
          mrace = case_when(
            mrace == 1 ~ "White", 
            mrace == 2 ~ "Black",
            mrace == 3 ~ "Asian",
            mrace == 4 ~ "Puerto Rican",
            mrace == 8 ~ "Other"
            ))

# Check for missing values?? ~drop_any
```

```{r}
model_1fit = lm(bwt ~ gaweeks, data = Birth_weight_df)
```

```{r}
Residual_predictions = Birth_weight_df %>% 
  modelr::add_residuals(model_1fit) %>% 
  modelr::add_predictions(model_1fit) %>%
  select(resid,pred)

  
Plot = Residual_predictions %>% ggplot(aes(x = resid, y = pred)) + 
  geom_point()
Plot

#X is residuals, y predictions ---> check plot 
```

Compare your model to two others:

-One using length at birth and gestational age as predictors (main effects only)
```{r}
model_2fit = lm(bwt ~ blength + gaweeks, data = Birth_weight_df)
#compare cross validation, graph
```

-One using head circumference, length, sex, and all interactions (including the three-way interaction) between these
```{r}
library(tidyverse)
library(modelr)
library(mgcv)

model_3fit = lm(bwt ~ bhead * blength * babysex, data = Birth_weight_df) 

cv_df = 
  crossv_mc(Birth_weight_df, 100) 

cv_df = 
  cv_df %>% 
  mutate(
   model_3fit  = map(train, ~lm(bwt ~ bhead * blength * babysex, data = Birth_weight_df)), 
   model_2fit = map(train, ~lm(bwt ~ blength + gaweeks, data = Birth_weight_df)),
   model_1fit = map(train, ~lm(bwt ~ gaweeks, data = Birth_weight_df))) %>%
  mutate(
    rmse_3fit = map2_dbl(model_3fit, test, ~rmse(model = .x, data = .y)),
    rmse_2fit = map2_dbl(model_2fit, test, ~rmse(model = .x, data = .y)),
    rmse_1fitl = map2_dbl(model_1fit, test, ~rmse(model = .x, data = .y)))

Compare_model_Plot = cv_df %>% 
  select(starts_with("rmse")) %>% 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") %>% 
  mutate(model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse)) + geom_violin()
Compare_model_Plot

```


##Problem 3
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

